### ISSUE TITLE
March release: Tweaks & Issues Checklist

### ISSUE THREAD

**Issue by neilneyman** [USDepartmentofLabor/Developer#26]
- [x] Buttons for sample & meta                                                          
- [x] Remove appchalenge info if present                                                 
- [x] Grab our code should go to "grab our code" section from beginner/exp page          
- [x] Labor Stats: nix try it out:                                                       
- [x] Labor Stats Buttons: Ios (itunes), android (google play store), grab the code (gith
- [x] Grab our code on homepage increase font size                                       
- [x] Change Apple ioS on Grab our Code to Obj-C                                         
- [x] Remove Career and Internships                                                      
- [x] **Beginner:** Learn More: github/DOLAPI/beginners-guide.html (include content local
- [x] **Beginner:** move speedometer down to align with text                             
- [x] **Beginner:** remove Conversions & Mobile accessibility test script.  Fix Timesheet spelling
- [x] **Beginner:** Left flush at top                                                    
- [x] **Experienced:** Delete Learn More Button, delete how our api works header Put paragraph under speedo &  links to right make blue larger and remove coffee image
- [x] **Experienced:** Change title to "Experienced Developers Guide"                    
- [x] Change "Dive in to Datasets" to Explore Our DAta  (also change on **Top Navbar**)  
- [x] **Top Navbar:** remove 'about the api'.  Use "our" api                             
- [x] No +Feedback link.                                                                 
- [x] **Datasets:** title in caps, bold, smaller font                                    
- [x] **Datasets:** links for tables if > 1                                              
- [x] **Datasets:** Sidebar: category at top                                             
- [x] **Datasets landing page:** column categories                                       
- [x] **Top Navbar:**API Keys link to admintools https://devtools.dol.gov/developer   
- [x] Add/Fix Page Titles

**Comment by spoonstein** [comment]
[ ] *Datasets:* Drop BLS from dataset prefix unless it's BLS Numbers
[ ] *Datasets:* Configure dataset tables to display and list tables if there is more than one table
[ ] *Datasets:* Nowrap on Data Type column for dataset tables
[ ] *Datasets:* Buttons in place of links for *Sample* and *Browse Metadata*

**Comment by spoonstein** [comment]
- [ ] **Homepage:** Labor Stats App - https://www.dol.gov/dol/apps/laborstats.htm 
- [ ] **Homepage:** Source for Stats App (both) https://github.com/USDepartmentofLabor?query=stats 
- [ ] **Beginners Guide:** Drop dataset sub navigation
- [ ] **Beginners Guide & Accessing the APIs Using .. :** Link up Request Authorization 
- [ ] **Accessing the APIs Using .. :** Drop dataset sub navigation
- [ ] **All Headings:** Drop colons at the end
- [ ] **Beginners Guide:** 
- [ ] **Experienced Developers Page:** Correct alignment and padding issues. Left align API Details/Get Help.
- [ ] **Include existing TOS as new page**
- [ ] **Dataset:** Correct styling for sub-navigation see: https://github.com/USDepartmentofLabor/Developer/issues/11
- [ ] **Header:** Drop the Beta flag
- [ ]  **Grab Our Code:** Center SDK listing (not left align)
- [ ] **Experienced Developer & Beginner Page:** Use existing black and white icons for mobile and web/desktop

**Comment by spoonstein** [comment]
**Experienced Developers Page Links**
- [ ] URLs - link to accessing API using HTTP req's
- [ ] Encoding - postpone until further notified
- [ ] Authentication - link to Beginners Guide anchor on Accessing the API
- [ ] Dates - postpone until further notified

**Comment by spoonstein** [comment]
**Beginners Page**
- [ ] Link to http://www.odata.org/ at the bottom where it's mentioned as OData.org
- [ ] Copy for Learn More section: Discover how our API works and how you can use it to access DOL data.

**All Pages**
- [ ] Ensure CSS is uppercasing content, don't uppercase using the keyboard

**Comment by neilneyman** [comment]
@spoonstein 
 
### Still Need

* Links for Homepage Mobile & Desktop
* Links for Experienced:
  * URLS
  * Authentication
  * Encoding
  * Dates
* Where to link the page: Accessing the apis using http requests.  We mentioned putting this among the above experienced page links -- need a title and icon for it then

**Comment by spoonstein** [comment]
Please add the second column to the footer. 

 <div class="large-3 columns line-b-peach">
    <p><strong>ABOUT THE SITE</strong></p>
    <ul role="navigation">
      <li><a href="/dol/foia/">Freedom of Information Act</a></li>
      <li><a href="/dol/privacynotice.htm">Privacy &amp; Security Statement</a></li>
      <li><a href="/dol/disclaim.htm">Disclaimers</a></li>
      <li><a href="/dol/aboutdol/website-policies.htm">Important Web Site Notices</a></li>
      <li><a href="/dol/aboutdol/plug-ins.htm">Plug-ins Used by DOL</a></li>
      <li><a href="/rss/">RSS Feeds from DOL</a></li>
      <li><a href="/dol/aboutdol/accessibility.htm">Accessibility Statement</a></li>
    </ul>
  </div>

**Comment by spoonstein** [comment]
@neilneyman for lower portions on #15 and #20 

**Mobile**
DOL Timesheet	https://github.com/USDepartmentofLabor/DOL-Timesheet
Labor Stats	https://github.com/USDepartmentofLabor?query=laborstat
OSHA Heat Safety	https://github.com/USDepartmentofLabor?query=heat-safety
Strategy Tracker	https://github.com/USDepartmentofLabor/StrategyTrackeriPad
	
**Web & Desktop**
API Status	https://github.com/USDepartmentofLabor/API-Status
JS Dashboard	https://github.com/USDepartmentofLabor/JS-Dashboard
OSHA Heat Safety	https://github.com/USDepartmentofLabor/OSHA-Heat-Safety
Was This Page Helpful	https://github.com/USDepartmentofLabor?query=helpful

**Comment by MikePulsiferDOL** [comment]
- [x] Grab Our Code: ColdFusion (no space between the two words)
- [x] Beginners Guide: Should there be an apostrophe?
- [x] Beginners Guide: Accessing the API is blue and looks like a link
- [x] Browse our Data: Clicking the Expanding Growth and Opportunities menu item has the menu obscure the footer (separate issue?)
- [x] Browser our Data: Health and Safety is displayed on the page and twice
- [ ] Grab our Code: shows only the SDKs.  Needs list of the other repos (mobile, web & desktop).  Include a link to https://github.com/USDepartmentofLabor for all of our repos, including those not categorized on this page.
- [ ] Header: Report Bugs: This is for API bugs, but this isn't obvious. Slight reword?
- [x] HTTP Requests page: example URLs are formatted like links, but aren't links.

**Comment by neilneyman** [comment]
1. [x] **sidebar** Hover Links:  underline and link blue
2. [ ] **sidebar** border colors
3. [x] **beginners-guide** remove request authorization page and paragraph
4. [x] **beginners-guide** convert accessing the api to button  Change accesing the api using http requests to "How to Customize your Request"
5. [x] **beginner's page** apostrophe:
6. [x] **experienced developer's** apostrophe
7. [x] **beginner's guide** apostrophe
8. [x] "View **Vets-100** Documentation" button instead of link  (top and bottom)
9. [x] google analytics
10. [x] **footer:** ask q & report bugz & TOS  above fork link (column 3)
11. [x] **footer:** column 3: title developer
12. [x] **sidebar menu:** move title closer to icon on left
13. [x] Was this page helpful? question mark (apps.html)  
14. [x] **homepage** Font size at bottom should match rest of text on page

**Comment by joey-spooner** [comment]
@neilneyman please spend some time this week closing out the remaining tasks on this issue.

**Comment by joey-spooner** [comment]
From checklist above. Please include update for "Report Bugs" to be "Report API Bugs" and update the Grab Our Code to reflect apps and a button to "Browse all DOL code" that points to https://github.com/USDepartmentofLabor
